#server:
#  port: 8081
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5454/countries_dev
#    username: postgres
#    password: p.postgres
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: false
#
#  cache:
#    type: redis
#  redis:
#    host: localhost
#    port: 6379
#
#cache:
#  config:
#    entryTtl: 60
#    countryNames:
#      entryTtl: 30
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      format_sql: true
#  servlet:
#    multipart:
#    max-file-size: 5MB
#    max-request-size: 5MB
#    file-size-threshold: 2KB
#
#    security:
#      jwt:
#        secret-key: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
#        expire-length: 3600000
#
#cloud:
#  aws:
#    accessKey:
#    secretKey:
#    region:
#      static: eu-west-1
#      auto: false
#    s3Bucket:
#      name: dev-slice-fund-logo
#
#spring:
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 1MB
#      max-request-size: 1MB
#
#
#

